version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db-agent
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ROOT_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - leftcurve_network
networks:
  leftcurve_network:
    name: leftcurve_network
